--drop table IF EXISTS users CASCADE;
--drop table IF EXISTS items CASCADE;
--drop table IF EXISTS orders CASCADE;
DROP ALL OBJECTS;

create TABLE IF NOT EXISTS users (
	user_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name VARCHAR NOT NULL,
	email VARCHAR NOT NULL unique,
	phone CHAR(12) NOT NULL,
	birthday DATE,
	is_vendor BOOLEAN NOT NULL,
	CONSTRAINT pk_users PRIMARY KEY (user_id),
	CONSTRAINT uq_user_email UNIQUE (email)
);

create TABLE IF NOT EXISTS items (
    item_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    is_available BOOLEAN NOT NULL,
    vendor_id INTEGER NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (item_id),
    CONSTRAINT fk_items_users FOREIGN KEY (vendor_id) REFERENCES users (user_id)
);

create TABLE IF NOT EXISTS orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id INTEGER NOT NULL,
    buyer_id INTEGER NOT NULL,
    status VARCHAR(15),
    created DATE,
    CONSTRAINT pk_order PRIMARY KEY (order_id),
    CONSTRAINT fk_orders_users FOREIGN KEY (buyer_id) REFERENCES users (user_id),
    CONSTRAINT fk_orders_items FOREIGN KEY (item_id) REFERENCES items (item_id)
);

--insert into users (user_id, name, email, phone, birthday, is_vendor)
--values (1, '{Алиса Анохина}', '{alisa@mail.ru}', '{89203127866}', DATE '1987-03-12', false),
--       (2, '{Борис Бунин}', '{boris@mail.com}', '{89303036754}', DATE '1999-05-13', true),
--       (3, '{Владимир Выготский}', '{vladimir@mail.com}', '{89204305464}', DATE '2001-12-20', false),
--       (4, '{Гена Горин}', '{gena@mail.ru}', '{89303404546}', DATE '1967-09-23', true),
--       (5, '{Дарья Дорохова}', '{daria@mail.ru}', '{89101189022}', DATE '2015-07-30', true);
--
--INSERT INTO items (item_id, name, description, is_available, vendor_id)
--VALUES (1, '{Елка новогодняя}', '{Все для праздника}', true, 4),
--       (2, '{Жакет женский}', '{Только ручная стирка}', true, 5),
--       (3, '{Зонт}', '{Зонт-трость прозрачный}', true, 5),
--       (4, '{Игра настольная}', '{Интеллектуальная игра для компании}', true, 4);
--
--insert into orders (order_id, item_id, buyer_id, status, created)
--values (1, 1, 2, '{IN_PROCESS}', '2024-08-05'),
--       (2, 2, 1, '{DELIVERED}', '2024-07-27'),
--       (3, 4, 3, '{DENIED}', '2024-08-03');